steps:
  - wait: ~
  - label: "deploy-static-site"
    key: "deploy-static-site"
    commands:
      - source /home/buildkite-agent/.local/bin/env
      - trifold status -v
      - trifold publish --delete
    agents:
      queue: "self-hosted-linux-x86-64"
    plugins:
      - docker:
          image: "402590802363.dkr.ecr.us-east-2.amazonaws.com/dev-react-builder:latest"
          workdir: /app
          mount-buildkite-agent: true
          propagate-environment: true
          propagate-uid-gid: true
          entrypoint: ""
          shell: ["/bin/bash", "-c"]
          environment:
            - "BUNNY_API_KEY"
    branches: "main"

secrets:
  - BUNNY_API_KEY